---
- hosts:
    - host1
    - host2
    - host3
    - host4
    - host5
    - host6
    - host7
    - host8
    - host9
    - host10
  gather_facts: True
  vars_files:
    - extra_vars.yml
  sudo: yes
  roles:
    - add_hostname
    - mysql
    - host_configure
    - config_mysql
    - setup_cluster