---

- name: Import Docker APT public key.
  apt_key:
    keyserver: "{{ docker_pubkey_server }}"
    id: "{{ docker_pubkey_id }}"
    state: present


- name: Install apt-transport-https if necessary.
  apt:
    name: apt-transport-https
    state: present


- name: Add the APT Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present

- name: Install Docker dependencies.
  package:
    name: linux-image-extra-virtual
    state: present

- name: Install the Docker Engine.
  package:
    name: docker-engine
    state: present

- name: Enable the Docker daemon as a service and start it.
  service:
    name: docker
    state: started
    enabled: yes
